import "@/shared/styles/global.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pc Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
}